-- Migration 017 — Sprint 0 audio uploads and Whisper transcripts.
--
-- Browser clients upload audio directly to a private Supabase Storage bucket.
-- Lumo Core then signs a short read URL for Lumo_ML_Service /transcribe,
-- stores the returned transcript, and lets the existing content indexer
-- embed redacted transcript chunks into content_embeddings for recall.
--
-- Rollback:
--   drop function if exists public.next_audio_transcript_embedding_batch(integer);
--   drop table if exists public.audio_transcripts;
--   drop table if exists public.audio_uploads;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'audio',
  'audio',
  false,
  209715200,
  array[
    'audio/mpeg',
    'audio/mp4',
    'audio/wav',
    'audio/x-wav',
    'audio/webm',
    'audio/ogg',
    'audio/aac',
    'audio/flac',
    'audio/x-m4a',
    'video/mp4',
    'video/quicktime',
    'video/webm'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.audio_uploads (
  id              text primary key,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  bucket          text not null default 'audio',
  storage_path    text not null unique,
  mime_type       text not null,
  size_bytes      bigint not null check (size_bytes > 0 and size_bytes <= 200 * 1024 * 1024),
  sha256          text not null,
  duration_ms     integer,
  language        text,
  status          text not null default 'pending_upload' check (
                    status in ('pending_upload', 'uploaded', 'transcribing', 'transcribed', 'failed')
                  ),
  transcript_id   bigint,
  error_text      text,
  created_at      timestamptz not null default now(),
  uploaded_at     timestamptz,
  transcribed_at  timestamptz,
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

create index if not exists audio_uploads_by_user
  on public.audio_uploads (user_id, created_at desc)
  where deleted_at is null;

create index if not exists audio_uploads_by_status
  on public.audio_uploads (status, updated_at)
  where deleted_at is null and status in ('uploaded', 'transcribing', 'failed');

create index if not exists audio_uploads_by_sha
  on public.audio_uploads (user_id, sha256)
  where deleted_at is null;

drop trigger if exists audio_uploads_touch_updated_at on public.audio_uploads;
create trigger audio_uploads_touch_updated_at
  before update on public.audio_uploads
  for each row execute function public.touch_updated_at();

create table if not exists public.audio_transcripts (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references public.profiles(id) on delete cascade,
  audio_upload_id   text not null references public.audio_uploads(id) on delete cascade,
  storage_path      text not null,
  transcript        text not null,
  segments          jsonb not null default '[]'::jsonb,
  language          text,
  duration_s        numeric,
  model             text not null,
  created_at        timestamptz not null default now(),
  unique (audio_upload_id)
);

create index if not exists audio_transcripts_by_user_recent
  on public.audio_transcripts (user_id, created_at desc);

create index if not exists audio_transcripts_by_upload
  on public.audio_transcripts (audio_upload_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'audio_uploads_transcript_fk'
      and conrelid = 'public.audio_uploads'::regclass
  ) then
    alter table public.audio_uploads
      add constraint audio_uploads_transcript_fk
      foreign key (transcript_id)
      references public.audio_transcripts(id)
      on delete set null;
  end if;
end $$;

create or replace function public.next_audio_transcript_embedding_batch(
  requested_limit integer default 100
)
returns table (
  id bigint,
  user_id uuid,
  audio_upload_id text,
  storage_path text,
  transcript text,
  segments jsonb,
  language text,
  duration_s numeric,
  model text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    t.id,
    t.user_id,
    t.audio_upload_id,
    t.storage_path,
    t.transcript,
    t.segments,
    t.language,
    t.duration_s,
    t.model,
    t.created_at
  from public.audio_transcripts t
  left join public.content_embedding_sources s
    on s.source_table = 'audio_transcripts'
   and s.source_row_id = t.id
  where
    auth.role() = 'service_role'
    and (
      s.source_row_id is null
      or (
        s.status = 'failed'
        and s.updated_at < now() - interval '1 hour'
      )
    )
  order by t.created_at desc, t.id desc
  limit greatest(1, least(coalesce(requested_limit, 100), 500));
$$;

revoke all on function public.next_audio_transcript_embedding_batch(integer) from public;
grant execute on function public.next_audio_transcript_embedding_batch(integer) to service_role;
