-- Migration 019 — Sprint 1 PDF document extraction and recall indexing.
--
-- Browser clients upload PDFs directly to a private Supabase Storage bucket.
-- Lumo Core signs a short read URL for Lumo_ML_Service /extract_pdf,
-- stores layout-aware pages/blocks, then indexes redacted page chunks into
-- content_embeddings with page_number metadata for recall citations.
--
-- Rollback:
--   drop function if exists public.next_pdf_document_embedding_batch(integer);
--   drop table if exists public.document_assets cascade;
--   drop table if exists public.pdf_documents cascade;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents',
  'documents',
  false,
  104857600,
  array['application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.document_assets (
  id              text primary key,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  bucket          text not null default 'documents',
  storage_path    text not null unique,
  filename        text not null,
  mime_type       text not null default 'application/pdf',
  size_bytes      bigint not null check (size_bytes > 0 and size_bytes <= 100 * 1024 * 1024),
  sha256          text not null,
  status          text not null default 'pending_upload' check (
                    status in ('pending_upload', 'uploaded', 'extracting', 'extracted', 'failed')
                  ),
  pdf_document_id bigint,
  error_text      text,
  created_at      timestamptz not null default now(),
  uploaded_at     timestamptz,
  extracted_at    timestamptz,
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

create index if not exists document_assets_by_user
  on public.document_assets (user_id, created_at desc)
  where deleted_at is null;

create index if not exists document_assets_by_status
  on public.document_assets (status, updated_at)
  where deleted_at is null and status in ('uploaded', 'extracting', 'failed');

create index if not exists document_assets_by_sha
  on public.document_assets (user_id, sha256)
  where deleted_at is null;

drop trigger if exists document_assets_touch_updated_at on public.document_assets;
create trigger document_assets_touch_updated_at
  before update on public.document_assets
  for each row execute function public.touch_updated_at();

create table if not exists public.pdf_documents (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references public.profiles(id) on delete cascade,
  document_asset_id text not null references public.document_assets(id) on delete cascade,
  storage_path      text not null,
  filename          text not null,
  pages             jsonb not null default '[]'::jsonb,
  total_pages       integer not null default 0 check (total_pages >= 0),
  language          text,
  created_at        timestamptz not null default now(),
  unique (document_asset_id)
);

create index if not exists pdf_documents_by_user_recent
  on public.pdf_documents (user_id, created_at desc);

create index if not exists pdf_documents_by_asset
  on public.pdf_documents (document_asset_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'document_assets_pdf_document_fk'
      and conrelid = 'public.document_assets'::regclass
  ) then
    alter table public.document_assets
      add constraint document_assets_pdf_document_fk
      foreign key (pdf_document_id)
      references public.pdf_documents(id)
      on delete set null;
  end if;
end $$;

create or replace function public.next_pdf_document_embedding_batch(
  requested_limit integer default 100
)
returns table (
  id bigint,
  user_id uuid,
  document_asset_id text,
  storage_path text,
  filename text,
  pages jsonb,
  total_pages integer,
  language text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    d.id,
    d.user_id,
    d.document_asset_id,
    d.storage_path,
    d.filename,
    d.pages,
    d.total_pages,
    d.language,
    d.created_at
  from public.pdf_documents d
  left join public.content_embedding_sources s
    on s.source_table = 'pdf_documents'
   and s.source_row_id = d.id
  where
    auth.role() = 'service_role'
    and (
      s.source_row_id is null
      or (
        s.status = 'failed'
        and s.updated_at < now() - interval '1 hour'
      )
    )
  order by d.created_at desc, d.id desc
  limit greatest(1, least(coalesce(requested_limit, 100), 500));
$$;

revoke all on function public.next_pdf_document_embedding_batch(integer) from public;
grant execute on function public.next_pdf_document_embedding_batch(integer) to service_role;
