-- Migration 020 — Sprint 1 CLIP image embeddings and recall summaries.
--
-- Browser clients upload images directly to a private Supabase Storage bucket.
-- Lumo Core signs a short read URL for Lumo_ML_Service /embed_image, stores
-- CLIP's 512-dim vector separately, then indexes the redacted label summary
-- into content_embeddings so normal recall can cite visual assets.
--
-- Rollback:
--   drop function if exists public.next_image_embedding_text_batch(integer);
--   drop table if exists public.image_assets cascade;
--   drop table if exists public.image_embeddings cascade;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'images',
  'images',
  false,
  26214400,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.image_assets (
  id                 text primary key,
  user_id            uuid not null references public.profiles(id) on delete cascade,
  bucket             text not null default 'images',
  storage_path       text not null unique,
  filename           text not null,
  mime_type          text not null,
  size_bytes         bigint not null check (size_bytes > 0 and size_bytes <= 25 * 1024 * 1024),
  sha256             text not null,
  width_px           integer,
  height_px          integer,
  status             text not null default 'pending_upload' check (
                       status in ('pending_upload', 'uploaded', 'embedding', 'embedded', 'failed')
                     ),
  image_embedding_id bigint,
  error_text         text,
  created_at         timestamptz not null default now(),
  uploaded_at        timestamptz,
  embedded_at        timestamptz,
  updated_at         timestamptz not null default now(),
  deleted_at         timestamptz
);

create index if not exists image_assets_by_user
  on public.image_assets (user_id, created_at desc)
  where deleted_at is null;

create index if not exists image_assets_by_status
  on public.image_assets (status, updated_at)
  where deleted_at is null and status in ('uploaded', 'embedding', 'failed');

create index if not exists image_assets_by_sha
  on public.image_assets (user_id, sha256)
  where deleted_at is null;

drop trigger if exists image_assets_touch_updated_at on public.image_assets;
create trigger image_assets_touch_updated_at
  before update on public.image_assets
  for each row execute function public.touch_updated_at();

create table if not exists public.image_embeddings (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references public.profiles(id) on delete cascade,
  image_asset_id    text not null references public.image_assets(id) on delete cascade,
  storage_path      text not null,
  filename          text not null,
  mime_type         text not null,
  model             text not null,
  dimensions        integer not null default 512 check (dimensions > 0),
  embedding         vector(512) not null,
  labels            jsonb not null default '[]'::jsonb,
  summary_text      text not null,
  content_hash      text not null,
  created_at        timestamptz not null default now(),
  unique (image_asset_id)
);

create index if not exists image_embeddings_by_user_recent
  on public.image_embeddings (user_id, created_at desc);

create index if not exists image_embeddings_by_asset
  on public.image_embeddings (image_asset_id);

create index if not exists image_embeddings_vector_cosine
  on public.image_embeddings using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'image_assets_image_embedding_fk'
      and conrelid = 'public.image_assets'::regclass
  ) then
    alter table public.image_assets
      add constraint image_assets_image_embedding_fk
      foreign key (image_embedding_id)
      references public.image_embeddings(id)
      on delete set null;
  end if;
end $$;

create or replace function public.next_image_embedding_text_batch(
  requested_limit integer default 100
)
returns table (
  id bigint,
  user_id uuid,
  image_asset_id text,
  storage_path text,
  filename text,
  mime_type text,
  model text,
  dimensions integer,
  labels jsonb,
  summary_text text,
  content_hash text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    e.id,
    e.user_id,
    e.image_asset_id,
    e.storage_path,
    e.filename,
    e.mime_type,
    e.model,
    e.dimensions,
    e.labels,
    e.summary_text,
    e.content_hash,
    e.created_at
  from public.image_embeddings e
  left join public.content_embedding_sources s
    on s.source_table = 'image_embeddings'
   and s.source_row_id = e.id::text
  where
    auth.role() = 'service_role'
    and (
      s.source_row_id is null
      or (
        s.status = 'failed'
        and s.updated_at < now() - interval '1 hour'
      )
    )
  order by e.created_at desc, e.id desc
  limit greatest(1, least(coalesce(requested_limit, 100), 500));
$$;

revoke all on function public.next_image_embedding_text_batch(integer) from public;
grant execute on function public.next_image_embedding_text_batch(integer) to service_role;
