-- Migration 023 — Sprint 3 durable mission execution substrate.
--
-- Phase 3 moves multi-agent work from one-shot chat responses into durable
-- missions that can pause for permissions, resume after OAuth/account setup,
-- require confirmation cards before side effects, and preserve an audit trail.
--
-- Rollback:
--   drop function if exists public.next_mission_step_for_execution(integer);
--   drop table if exists public.mission_execution_events;
--   drop table if exists public.mission_steps;
--   drop table if exists public.missions;

create table if not exists public.missions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  session_id  text,
  intent_text text not null,
  state       text not null default 'draft' check (state in (
                'draft',
                'awaiting_permissions',
                'awaiting_user_input',
                'ready',
                'executing',
                'awaiting_confirmation',
                'completed',
                'failed',
                'rolled_back'
              )),
  plan        jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists missions_by_user_state_updated
  on public.missions (user_id, state, updated_at desc);

create index if not exists missions_by_session
  on public.missions (session_id, updated_at desc)
  where session_id is not null;

create index if not exists missions_ready_for_execution
  on public.missions (updated_at asc)
  where state = 'ready';

drop trigger if exists missions_touch_updated_at on public.missions;
create trigger missions_touch_updated_at
  before update on public.missions
  for each row execute function public.touch_updated_at();

alter table public.missions enable row level security;
revoke all on public.missions from anon, authenticated;
grant all on public.missions to service_role;

create table if not exists public.mission_steps (
  id                   uuid primary key default gen_random_uuid(),
  mission_id           uuid not null references public.missions(id) on delete cascade,
  step_order           integer not null check (step_order >= 0),
  agent_id             text not null,
  tool_name            text not null,
  reversibility        text not null check (reversibility in (
                         'reversible',
                         'compensating',
                         'irreversible'
                       )),
  status               text not null default 'pending' check (status in (
                         'pending',
                         'running',
                         'succeeded',
                         'failed',
                         'rolled_back',
                         'skipped'
                       )),
  inputs               jsonb not null default '{}'::jsonb,
  outputs              jsonb not null default '{}'::jsonb,
  confirmation_card_id text,
  started_at           timestamptz,
  finished_at          timestamptz,
  error_text           text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (mission_id, step_order)
);

create index if not exists mission_steps_by_mission_order
  on public.mission_steps (mission_id, step_order asc);

create index if not exists mission_steps_by_status
  on public.mission_steps (status, created_at asc);

create index if not exists mission_steps_by_agent_tool
  on public.mission_steps (agent_id, tool_name, created_at desc);

drop trigger if exists mission_steps_touch_updated_at on public.mission_steps;
create trigger mission_steps_touch_updated_at
  before update on public.mission_steps
  for each row execute function public.touch_updated_at();

alter table public.mission_steps enable row level security;
revoke all on public.mission_steps from anon, authenticated;
grant all on public.mission_steps to service_role;

create table if not exists public.mission_execution_events (
  id         bigint generated by default as identity primary key,
  mission_id uuid not null references public.missions(id) on delete cascade,
  step_id    uuid references public.mission_steps(id) on delete set null,
  event_type text not null,
  payload    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists mission_execution_events_by_mission
  on public.mission_execution_events (mission_id, created_at asc);

create index if not exists mission_execution_events_by_step
  on public.mission_execution_events (step_id, created_at asc)
  where step_id is not null;

create index if not exists mission_execution_events_by_type
  on public.mission_execution_events (event_type, created_at desc);

alter table public.mission_execution_events enable row level security;
revoke all on public.mission_execution_events from anon, authenticated;
grant all on public.mission_execution_events to service_role;
grant usage, select on sequence public.mission_execution_events_id_seq to service_role;

-- Service-role RPC: atomically claim the next runnable mission steps. A step
-- is runnable only when its mission is ready/executing and all prior steps in
-- the mission have either succeeded or been intentionally skipped.
create or replace function public.next_mission_step_for_execution(
  requested_limit integer default 10
)
returns table (
  id uuid,
  mission_id uuid,
  user_id uuid,
  step_order integer,
  agent_id text,
  tool_name text,
  reversibility text,
  inputs jsonb,
  confirmation_card_id text
)
language sql
security definer
set search_path = public
as $$
  with runnable as (
    select s.id
    from public.mission_steps s
    join public.missions m on m.id = s.mission_id
    where
      auth.role() = 'service_role'
      and m.state in ('ready', 'executing')
      and s.status = 'pending'
      and not exists (
        select 1
        from public.mission_steps prior
        where
          prior.mission_id = s.mission_id
          and prior.step_order < s.step_order
          and prior.status not in ('succeeded', 'skipped')
      )
    order by m.updated_at asc, s.step_order asc
    for update of s skip locked
    limit greatest(1, least(coalesce(requested_limit, 10), 50))
  ),
  claimed as (
    update public.mission_steps s
    set
      status = 'running',
      started_at = coalesce(s.started_at, now()),
      updated_at = now()
    from runnable r
    where s.id = r.id
    returning
      s.id,
      s.mission_id,
      s.step_order,
      s.agent_id,
      s.tool_name,
      s.reversibility,
      s.inputs,
      s.confirmation_card_id
  ),
  touched_missions as (
    update public.missions m
    set
      state = 'executing',
      updated_at = now()
    from (select distinct mission_id from claimed) c
    where
      m.id = c.mission_id
      and m.state = 'ready'
    returning m.id
  )
  select
    c.id,
    c.mission_id,
    m.user_id,
    c.step_order,
    c.agent_id,
    c.tool_name,
    c.reversibility,
    c.inputs,
    c.confirmation_card_id
  from claimed c
  join public.missions m on m.id = c.mission_id
  order by m.updated_at asc, c.step_order asc;
$$;

revoke all on function public.next_mission_step_for_execution(integer) from public;
grant execute on function public.next_mission_step_for_execution(integer) to service_role;
