-- Migration 025 — Sprint 3 durable mission rollback.
--
-- D5 adds explicit rollback execution for durable missions. Rollback is a
-- separate worker from the forward executor: missions enter rolling_back via a
-- user/admin action or a future event bus trigger, and the rollback cron claims
-- compensating actions in reverse step_order.
--
-- Rollback:
--   drop function if exists public.next_rollback_step_for_execution(integer);
--   drop table if exists public.mission_step_rollback_attempts;
--   alter table public.mission_steps drop constraint if exists mission_steps_status_check;
--   alter table public.mission_steps add constraint mission_steps_status_check
--     check (status in ('pending','awaiting_confirmation','ready','running','succeeded','failed','rolled_back','skipped'));
--   alter table public.missions drop constraint if exists missions_state_check;
--   alter table public.missions add constraint missions_state_check
--     check (state in ('draft','awaiting_permissions','awaiting_user_input','ready','executing','awaiting_confirmation','completed','failed','rolled_back'));

alter table public.missions
  drop constraint if exists missions_state_check;

alter table public.missions
  add constraint missions_state_check
  check (state in (
    'draft',
    'awaiting_permissions',
    'awaiting_user_input',
    'ready',
    'executing',
    'awaiting_confirmation',
    'rolling_back',
    'completed',
    'failed',
    'rolled_back'
  ));

alter table public.mission_steps
  drop constraint if exists mission_steps_status_check;

alter table public.mission_steps
  add constraint mission_steps_status_check
  check (status in (
    'pending',
    'awaiting_confirmation',
    'ready',
    'running',
    'succeeded',
    'failed',
    'rollback_failed',
    'rolled_back',
    'skipped'
  ));

create table if not exists public.mission_step_rollback_attempts (
  id                bigint generated by default as identity primary key,
  mission_id        uuid not null references public.missions(id) on delete cascade,
  step_id           uuid not null references public.mission_steps(id) on delete cascade,
  attempt           integer not null default 1 check (attempt >= 1),
  compensating_tool text,
  rendered_inputs   jsonb not null default '{}'::jsonb,
  status            text not null check (status in ('running','succeeded','failed','skipped')),
  error_text        text,
  started_at        timestamptz not null default now(),
  finished_at       timestamptz,
  created_at        timestamptz not null default now(),
  unique (step_id, attempt)
);

create index if not exists mission_steps_by_rollback_status
  on public.mission_steps (mission_id, step_order desc)
  where status in ('succeeded', 'rollback_failed');

create index if not exists missions_rolling_back_for_execution
  on public.missions (updated_at asc)
  where state = 'rolling_back';

create index if not exists mission_step_rollback_attempts_by_mission
  on public.mission_step_rollback_attempts (mission_id, created_at asc);

alter table public.mission_step_rollback_attempts enable row level security;
revoke all on public.mission_step_rollback_attempts from anon, authenticated;
grant all on public.mission_step_rollback_attempts to service_role;
grant usage, select on sequence public.mission_step_rollback_attempts_id_seq to service_role;

-- Service-role RPC: atomically claim the next rollback step per mission in
-- reverse step_order. A step is claimable only after every later successful
-- step already has a terminal rollback event.
create or replace function public.next_rollback_step_for_execution(
  requested_limit integer default 10
)
returns table (
  id uuid,
  mission_id uuid,
  user_id uuid,
  step_order integer,
  agent_id text,
  tool_name text,
  reversibility text,
  inputs jsonb,
  outputs jsonb,
  finished_at timestamptz,
  confirmation_card_id text
)
language sql
security definer
set search_path = public
as $$
  with candidates as (
    select s.id
    from public.mission_steps s
    join public.missions m on m.id = s.mission_id
    where
      auth.role() = 'service_role'
      and m.state = 'rolling_back'
      and s.status in ('succeeded', 'rollback_failed')
      and not exists (
        select 1
        from public.mission_execution_events e
        where
          e.step_id = s.id
          and e.event_type in (
            'rollback_step_succeeded',
            'rollback_step_failed',
            'rollback_step_skipped'
          )
      )
      and not exists (
        select 1
        from public.mission_steps later
        where
          later.mission_id = s.mission_id
          and later.step_order > s.step_order
          and later.status in ('succeeded', 'rollback_failed')
          and not exists (
            select 1
            from public.mission_execution_events le
            where
              le.step_id = later.id
              and le.event_type in (
                'rollback_step_succeeded',
                'rollback_step_failed',
                'rollback_step_skipped'
              )
          )
      )
    order by m.updated_at asc, s.step_order desc
    for update of s skip locked
    limit greatest(1, least(coalesce(requested_limit, 10), 50))
  ),
  claimed as (
    insert into public.mission_step_rollback_attempts (
      mission_id,
      step_id,
      attempt,
      status
    )
    select
      s.mission_id,
      s.id,
      1,
      'running'
    from candidates c
    join public.mission_steps s on s.id = c.id
    on conflict (step_id, attempt) do nothing
    returning step_id
  )
  select
    s.id,
    s.mission_id,
    m.user_id,
    s.step_order,
    s.agent_id,
    s.tool_name,
    s.reversibility,
    s.inputs,
    s.outputs,
    s.finished_at,
    s.confirmation_card_id
  from claimed c
  join public.mission_steps s on s.id = c.step_id
  join public.missions m on m.id = s.mission_id
  order by m.updated_at asc, s.step_order desc;
$$;

revoke all on function public.next_rollback_step_for_execution(integer) from public;
grant execute on function public.next_rollback_step_for_execution(integer) to service_role;
