-- Migration 039 — COST-1 metering, budgets, and rollups.
--
-- Implements docs/specs/sprint-4-cost-1-metering-budgets.md and ADR-016:
--   - per-invocation agent cost ledger
--   - per-user budget tier/cap rows
--   - daily/monthly spend rollups for fast budget checks
--   - digest-delivery idempotency keys for COST-1 email crons
--
-- Rollback:
--   drop trigger if exists agent_cost_log_touch_updated_at on public.agent_cost_log;
--   drop trigger if exists agent_cost_log_retry_safe_no_delete on public.agent_cost_log;
--   drop trigger if exists agent_cost_log_retry_safe_no_identity_update on public.agent_cost_log;
--   drop function if exists public.agent_cost_log_retry_safe_append_only();
--   drop trigger if exists user_budget_tiers_touch_updated_at on public.user_budget_tiers;
--   drop trigger if exists user_cost_rollups_daily_touch_updated_at on public.user_cost_rollups_daily;
--   drop trigger if exists user_cost_rollups_monthly_touch_updated_at on public.user_cost_rollups_monthly;
--   drop trigger if exists user_cost_digest_deliveries_touch_updated_at on public.user_cost_digest_deliveries;
--   drop trigger if exists on_profile_created_budget_tier on public.profiles;
--   drop function if exists public.tg_handle_new_profile_budget_tier();
--   drop index if exists public.agent_cost_log_by_request_id;
--   drop index if exists public.agent_cost_log_by_user_day;
--   drop index if exists public.agent_cost_log_by_user_agent_day;
--   drop index if exists public.agent_cost_log_by_agent_day;
--   drop index if exists public.agent_cost_log_by_mission_step;
--   drop index if exists public.agent_cost_log_budget_aborts;
--   drop index if exists public.user_cost_rollups_daily_by_date;
--   drop index if exists public.user_cost_rollups_monthly_by_month;
--   drop index if exists public.user_cost_digest_deliveries_by_due;
--   drop table if exists public.user_cost_digest_deliveries;
--   drop table if exists public.user_cost_rollups_monthly;
--   drop table if exists public.user_cost_rollups_daily;
--   drop table if exists public.user_budget_tiers;
--   drop table if exists public.agent_cost_log;

-- Per-invocation cost ledger. One row per request_id; retries reconcile the
-- same row rather than appending attempts. Identity columns are immutable.
create table if not exists public.agent_cost_log (
  id                         bigint generated by default as identity primary key,
  request_id                 uuid not null,
  user_id                    uuid not null references public.profiles(id) on delete cascade,
  agent_id                   text not null,
  agent_version              text not null,
  capability_id              text,
  mission_id                 uuid references public.missions(id) on delete set null,
  mission_step_id            uuid references public.mission_steps(id) on delete set null,
  model_used                 text,
  prompt_tokens              integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens          integer not null default 0 check (completion_tokens >= 0),
  brain_calls_usd            numeric(12,6) not null default 0 check (brain_calls_usd >= 0),
  brain_call_count           integer not null default 0 check (brain_call_count >= 0),
  model_tokens_input         integer not null default 0 check (model_tokens_input >= 0),
  model_tokens_output        integer not null default 0 check (model_tokens_output >= 0),
  model_tokens_cost_usd      numeric(12,6) not null default 0 check (model_tokens_cost_usd >= 0),
  connector_calls            integer not null default 0 check (connector_calls >= 0),
  connector_calls_usd        numeric(12,6) not null default 0 check (connector_calls_usd >= 0),
  cost_usd_total             numeric(12,6) not null default 0 check (cost_usd_total >= 0),
  cost_usd_platform          numeric(12,6) not null default 0 check (cost_usd_platform >= 0),
  cost_usd_developer_share   numeric(12,6) not null default 0 check (cost_usd_developer_share >= 0),
  total_usd                  numeric(12,6) not null default 0 check (total_usd >= 0),
  status                     text not null default 'completed'
    check (status in ('completed','aborted_budget','aborted_error')),
  evidence                   jsonb not null default '{}'::jsonb,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),
  unique (request_id),
  check (cost_usd_total >= cost_usd_platform + cost_usd_developer_share),
  check (total_usd >= brain_calls_usd + model_tokens_cost_usd + connector_calls_usd)
);

comment on table public.agent_cost_log is
  'COST-1 per-invocation ledger. Retried request_ids may update cost/status fields, but identity columns are immutable.';
comment on column public.agent_cost_log.request_id is
  'ADR-013 invocation idempotency key; unique so retries reconcile one invocation row.';
comment on column public.agent_cost_log.evidence is
  'Structured cost evidence, e.g. fallback_model_used, forecast_usd, connector_call breakdown.';

create index if not exists agent_cost_log_by_request_id
  on public.agent_cost_log (request_id);

create index if not exists agent_cost_log_by_user_day
  on public.agent_cost_log (user_id, created_at desc);

create index if not exists agent_cost_log_by_user_agent_day
  on public.agent_cost_log (user_id, agent_id, created_at desc);

create index if not exists agent_cost_log_by_agent_day
  on public.agent_cost_log (agent_id, created_at desc);

create index if not exists agent_cost_log_by_mission_step
  on public.agent_cost_log (mission_step_id)
  where mission_step_id is not null;

create index if not exists agent_cost_log_budget_aborts
  on public.agent_cost_log (user_id, created_at desc)
  where status = 'aborted_budget';

drop trigger if exists agent_cost_log_touch_updated_at on public.agent_cost_log;
create trigger agent_cost_log_touch_updated_at
  before update on public.agent_cost_log
  for each row execute function public.touch_updated_at();

create or replace function public.agent_cost_log_retry_safe_append_only()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (tg_op = 'UPDATE') then
    if old.request_id is distinct from new.request_id
       or old.user_id is distinct from new.user_id
       or old.agent_id is distinct from new.agent_id
       or old.agent_version is distinct from new.agent_version
       or old.capability_id is distinct from new.capability_id
       or old.mission_id is distinct from new.mission_id
       or old.mission_step_id is distinct from new.mission_step_id
       or old.created_at is distinct from new.created_at then
      raise exception 'AGENT_COST_LOG_IDENTITY_IMMUTABLE'
        using hint = 'Retries may reconcile cost/status for the same request_id, but invocation identity fields are immutable';
    end if;
    return new;
  end if;

  if (tg_op = 'DELETE') then
    if current_setting('lumo.allow_agent_cost_log_delete', true) <> 'true' then
      raise exception 'AGENT_COST_LOG_APPEND_ONLY'
        using hint = 'agent_cost_log is append-only except account-deletion cascade';
    end if;
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists agent_cost_log_retry_safe_no_identity_update on public.agent_cost_log;
create trigger agent_cost_log_retry_safe_no_identity_update
  before update on public.agent_cost_log
  for each row execute function public.agent_cost_log_retry_safe_append_only();

drop trigger if exists agent_cost_log_retry_safe_no_delete on public.agent_cost_log;
create trigger agent_cost_log_retry_safe_no_delete
  before delete on public.agent_cost_log
  for each row execute function public.agent_cost_log_retry_safe_append_only();

-- Per-user tier/cap configuration. Scope-specific caps remain in
-- agent_scope_grants.constraints from PERM-1; this table is the user-wide
-- budget layer from ADR-016.
create table if not exists public.user_budget_tiers (
  user_id                  uuid primary key references public.profiles(id) on delete cascade,
  tier                     text not null default 'free'
    check (tier in ('free','pro','enterprise')),
  daily_cap_usd            numeric(10,2) not null default 0.50 check (daily_cap_usd >= 0),
  monthly_cap_usd          numeric(10,2) not null default 5.00 check (monthly_cap_usd >= 0),
  daily_cap_override_usd   numeric(10,2) check (daily_cap_override_usd is null or daily_cap_override_usd >= 0),
  monthly_cap_override_usd numeric(10,2) check (monthly_cap_override_usd is null or monthly_cap_override_usd >= 0),
  soft_cap                 boolean not null default false,
  effective_from           timestamptz not null default now(),
  effective_until          timestamptz,
  notes                    text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  check (effective_until is null or effective_until > effective_from)
);

comment on table public.user_budget_tiers is
  'COST-1 per-user daily/monthly budget tier. Enterprise can use soft caps and override columns.';

drop trigger if exists user_budget_tiers_touch_updated_at on public.user_budget_tiers;
create trigger user_budget_tiers_touch_updated_at
  before update on public.user_budget_tiers
  for each row execute function public.touch_updated_at();

create or replace function public.tg_handle_new_profile_budget_tier()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_budget_tiers (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_profile_created_budget_tier on public.profiles;
create trigger on_profile_created_budget_tier
  after insert on public.profiles
  for each row execute function public.tg_handle_new_profile_budget_tier();

insert into public.user_budget_tiers (user_id)
  select p.id
  from public.profiles p
  left join public.user_budget_tiers ubt on ubt.user_id = p.id
  where ubt.user_id is null;

-- Rollups are materialized by COST-1 crons so dispatch checks don't scan the
-- full cost ledger on every invocation.
create table if not exists public.user_cost_rollups_daily (
  user_id                  uuid not null references public.profiles(id) on delete cascade,
  local_date               date not null,
  window_start_at          timestamptz not null,
  window_end_at            timestamptz not null,
  invocation_count         integer not null default 0 check (invocation_count >= 0),
  aborted_budget_count     integer not null default 0 check (aborted_budget_count >= 0),
  aborted_error_count      integer not null default 0 check (aborted_error_count >= 0),
  fallback_count           integer not null default 0 check (fallback_count >= 0),
  prompt_tokens            integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens        integer not null default 0 check (completion_tokens >= 0),
  cost_usd_total           numeric(12,6) not null default 0 check (cost_usd_total >= 0),
  cost_usd_platform        numeric(12,6) not null default 0 check (cost_usd_platform >= 0),
  cost_usd_developer_share numeric(12,6) not null default 0 check (cost_usd_developer_share >= 0),
  top_agents               jsonb not null default '[]'::jsonb,
  capability_breakdown     jsonb not null default '{}'::jsonb,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  primary key (user_id, local_date),
  check (window_end_at > window_start_at),
  check (cost_usd_total >= cost_usd_platform + cost_usd_developer_share)
);

create index if not exists user_cost_rollups_daily_by_date
  on public.user_cost_rollups_daily (local_date desc, user_id);

drop trigger if exists user_cost_rollups_daily_touch_updated_at on public.user_cost_rollups_daily;
create trigger user_cost_rollups_daily_touch_updated_at
  before update on public.user_cost_rollups_daily
  for each row execute function public.touch_updated_at();

create table if not exists public.user_cost_rollups_monthly (
  user_id                  uuid not null references public.profiles(id) on delete cascade,
  month_start              date not null,
  window_start_at          timestamptz not null,
  window_end_at            timestamptz not null,
  invocation_count         integer not null default 0 check (invocation_count >= 0),
  aborted_budget_count     integer not null default 0 check (aborted_budget_count >= 0),
  aborted_error_count      integer not null default 0 check (aborted_error_count >= 0),
  fallback_count           integer not null default 0 check (fallback_count >= 0),
  prompt_tokens            integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens        integer not null default 0 check (completion_tokens >= 0),
  cost_usd_total           numeric(12,6) not null default 0 check (cost_usd_total >= 0),
  cost_usd_platform        numeric(12,6) not null default 0 check (cost_usd_platform >= 0),
  cost_usd_developer_share numeric(12,6) not null default 0 check (cost_usd_developer_share >= 0),
  top_agents               jsonb not null default '[]'::jsonb,
  capability_breakdown     jsonb not null default '{}'::jsonb,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  primary key (user_id, month_start),
  check (window_end_at > window_start_at),
  check (cost_usd_total >= cost_usd_platform + cost_usd_developer_share),
  check (extract(day from month_start) = 1)
);

create index if not exists user_cost_rollups_monthly_by_month
  on public.user_cost_rollups_monthly (month_start desc, user_id);

drop trigger if exists user_cost_rollups_monthly_touch_updated_at on public.user_cost_rollups_monthly;
create trigger user_cost_rollups_monthly_touch_updated_at
  before update on public.user_cost_rollups_monthly
  for each row execute function public.touch_updated_at();

-- Idempotency table for daily/monthly digest crons.
create table if not exists public.user_cost_digest_deliveries (
  user_id             uuid not null references public.profiles(id) on delete cascade,
  digest_type         text not null check (digest_type in ('daily','monthly')),
  period_start        date not null,
  period_end          date not null,
  spend_usd           numeric(12,6) not null default 0 check (spend_usd >= 0),
  delivery_state      text not null default 'pending'
    check (delivery_state in ('pending','sent','skipped','failed')),
  notification_id     uuid,
  error_text          text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  sent_at             timestamptz,
  primary key (user_id, digest_type, period_start),
  check (period_end >= period_start)
);

create index if not exists user_cost_digest_deliveries_by_due
  on public.user_cost_digest_deliveries (digest_type, delivery_state, period_start);

drop trigger if exists user_cost_digest_deliveries_touch_updated_at on public.user_cost_digest_deliveries;
create trigger user_cost_digest_deliveries_touch_updated_at
  before update on public.user_cost_digest_deliveries
  for each row execute function public.touch_updated_at();

alter table public.agent_cost_log enable row level security;
alter table public.user_budget_tiers enable row level security;
alter table public.user_cost_rollups_daily enable row level security;
alter table public.user_cost_rollups_monthly enable row level security;
alter table public.user_cost_digest_deliveries enable row level security;

revoke all on public.agent_cost_log from anon, authenticated;
revoke all on public.user_budget_tiers from anon, authenticated;
revoke all on public.user_cost_rollups_daily from anon, authenticated;
revoke all on public.user_cost_rollups_monthly from anon, authenticated;
revoke all on public.user_cost_digest_deliveries from anon, authenticated;

grant all on public.agent_cost_log to service_role;
grant all on public.user_budget_tiers to service_role;
grant all on public.user_cost_rollups_daily to service_role;
grant all on public.user_cost_rollups_monthly to service_role;
grant all on public.user_cost_digest_deliveries to service_role;

grant usage, select on sequence public.agent_cost_log_id_seq to service_role;

grant select on public.agent_cost_log to authenticated;
grant select on public.user_budget_tiers to authenticated;
grant select on public.user_cost_rollups_daily to authenticated;
grant select on public.user_cost_rollups_monthly to authenticated;

drop policy if exists agent_cost_log_select_own on public.agent_cost_log;
create policy agent_cost_log_select_own on public.agent_cost_log
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists user_budget_tiers_select_own on public.user_budget_tiers;
create policy user_budget_tiers_select_own on public.user_budget_tiers
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists user_cost_rollups_daily_select_own on public.user_cost_rollups_daily;
create policy user_cost_rollups_daily_select_own on public.user_cost_rollups_daily
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists user_cost_rollups_monthly_select_own on public.user_cost_rollups_monthly;
create policy user_cost_rollups_monthly_select_own on public.user_cost_rollups_monthly
  for select
  to authenticated
  using ((select auth.uid()) = user_id);
