-- Migration 042 — DOCS feedback substrate.
--
-- Implements docs/specs/sprint-4-docs.md:
--   - per-page helpfulness feedback for docs.lumo.rentals/agents
--   - anonymous or signed-in attribution without public reads
--   - weekly digest input for the server-side docs feedback cron
--
-- Rollback:
--   drop trigger if exists docs_page_feedback_append_only_guard on public.docs_page_feedback;
--   drop function if exists public.docs_page_feedback_append_only();
--   drop index if exists public.docs_page_feedback_by_actor;
--   drop index if exists public.docs_page_feedback_by_page;
--   drop table if exists public.docs_page_feedback;

create table if not exists public.docs_page_feedback (
  id            bigint generated by default as identity primary key,
  page_id       text not null
                  check (
                    length(page_id) between 1 and 180
                    and page_id !~ '(^|/)\.\.(/|$)'
                    and page_id ~ '^[A-Za-z0-9][A-Za-z0-9/_-]*$'
                  ),
  user_id       uuid references public.profiles(id) on delete set null,
  anonymous_id  text
                  check (
                    anonymous_id is null
                    or (length(anonymous_id) between 16 and 128 and anonymous_id ~ '^[a-f0-9:._-]+$')
                  ),
  score         smallint not null check (score in (-1, 1)),
  free_text     text check (free_text is null or length(free_text) <= 5000),
  url_referrer  text check (url_referrer is null or length(url_referrer) <= 2048),
  user_agent    text check (user_agent is null or length(user_agent) <= 1024),
  created_at    timestamptz not null default now(),
  check (user_id is not null or anonymous_id is not null)
);

comment on table public.docs_page_feedback is
  'DOCS sprint feedback rows from docs.lumo.rentals/agents. Written by the service-role feedback API; consumed by the weekly digest cron.';
comment on column public.docs_page_feedback.page_id is
  'Stable docs page identifier, for example developers/04-scopes-and-permissions.';
comment on column public.docs_page_feedback.anonymous_id is
  'One-way visitor hash generated server-side from request metadata for unauthenticated feedback dedupe.';
comment on column public.docs_page_feedback.score is
  'Helpfulness vote: 1 for helpful, -1 for not helpful.';

create index if not exists docs_page_feedback_by_page
  on public.docs_page_feedback (page_id, created_at desc);

create index if not exists docs_page_feedback_by_actor
  on public.docs_page_feedback (coalesce(user_id::text, anonymous_id), page_id, created_at desc);

create or replace function public.docs_page_feedback_append_only()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (tg_op = 'UPDATE') then
    raise exception 'DOCS_PAGE_FEEDBACK_APPEND_ONLY'
      using hint = 'Insert a new feedback row instead of mutating historical docs feedback.';
  end if;

  if (tg_op = 'DELETE') then
    if current_setting('lumo.allow_docs_feedback_delete', true) <> 'true' then
      raise exception 'DOCS_PAGE_FEEDBACK_DELETE_FORBIDDEN'
        using hint = 'Docs feedback is digest input; only privacy/account-deletion jobs may remove rows.';
    end if;
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists docs_page_feedback_append_only_guard on public.docs_page_feedback;
create trigger docs_page_feedback_append_only_guard
  before update or delete on public.docs_page_feedback
  for each row execute function public.docs_page_feedback_append_only();

alter table public.docs_page_feedback enable row level security;

revoke all on public.docs_page_feedback from anon, authenticated;
grant select, insert, delete on public.docs_page_feedback to service_role;
grant usage, select on sequence public.docs_page_feedback_id_seq to service_role;
