-- Migration 044 — PERF-1+2 agent request timings.
--
-- Implements docs/specs/lumo-jarvis-master-roadmap.md §5:
--   - per-phase orchestrator timing spans
--   - bucket-aware latency analysis for fast_path / tool_path / reasoning_path
--   - /admin/perf percentile and slow-turn drill-down substrate
--
-- Rollback:
--   drop trigger if exists agent_request_timings_append_only_guard on public.agent_request_timings;
--   drop function if exists public.agent_request_timings_append_only();
--   drop index if exists public.agent_request_timings_by_request;
--   drop index if exists public.agent_request_timings_by_bucket_started;
--   drop index if exists public.agent_request_timings_by_phase_started;
--   drop table if exists public.agent_request_timings;

create table if not exists public.agent_request_timings (
  id          bigint generated by default as identity primary key,
  request_id  text not null
                check (
                  length(request_id) between 1 and 200
                  and request_id !~ '[[:space:]]'
                ),
  phase       text not null
                check (
                  phase in (
                    'pre_llm_data_load',
                    'intelligence_pass',
                    'system_prompt_build',
                    'llm_first_token',
                    'llm_total',
                    'tool_dispatch',
                    'post_processing',
                    'total'
                  )
                ),
  bucket      text not null default 'reasoning_path'
                check (bucket in ('fast_path','tool_path','reasoning_path')),
  started_at  timestamptz not null,
  ended_at    timestamptz not null,
  duration_ms integer generated always as (
                greatest(
                  0,
                  floor(extract(epoch from (ended_at - started_at)) * 1000)::integer
                )
              ) stored,
  metadata    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  check (ended_at >= started_at),
  check (jsonb_typeof(metadata) = 'object')
);

comment on table public.agent_request_timings is
  'PERF-1 per-phase orchestrator span timings. Written by the server-side orchestrator; read by the admin performance dashboard.';
comment on column public.agent_request_timings.request_id is
  'Stable per-turn request identifier used to group all spans for a chat/orchestrator turn.';
comment on column public.agent_request_timings.bucket is
  'PERF-2 routing bucket assigned by intent classifier/model router.';
comment on column public.agent_request_timings.duration_ms is
  'Generated duration in milliseconds from started_at/ended_at; app code never writes this value.';
comment on column public.agent_request_timings.metadata is
  'Bounded span metadata such as tool_name, model_used, cache tokens, error code, and provider. Do not store prompts or user message bodies.';

create index if not exists agent_request_timings_by_phase_started
  on public.agent_request_timings (phase, started_at desc);

create index if not exists agent_request_timings_by_bucket_started
  on public.agent_request_timings (bucket, started_at desc);

create index if not exists agent_request_timings_by_request
  on public.agent_request_timings (request_id, started_at asc, id asc);

create or replace function public.agent_request_timings_append_only()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if (tg_op = 'UPDATE') then
    raise exception 'AGENT_REQUEST_TIMINGS_APPEND_ONLY'
      using hint = 'Insert a new timing span instead of mutating historical performance evidence.';
  end if;

  if (tg_op = 'DELETE') then
    if current_setting('lumo.allow_agent_request_timing_delete', true) <> 'true' then
      raise exception 'AGENT_REQUEST_TIMINGS_DELETE_FORBIDDEN'
        using hint = 'Timing spans are observability evidence; only retention/privacy jobs may delete them.';
    end if;
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists agent_request_timings_append_only_guard on public.agent_request_timings;
create trigger agent_request_timings_append_only_guard
  before update or delete on public.agent_request_timings
  for each row execute function public.agent_request_timings_append_only();

alter table public.agent_request_timings enable row level security;

revoke all on public.agent_request_timings from anon, authenticated;
grant select, insert, delete on public.agent_request_timings to service_role;
grant usage, select on sequence public.agent_request_timings_id_seq to service_role;

-- Admin reads are intentionally mediated through service-role API routes after
-- the existing application-level admin gate. Browser clients get no direct
-- PostgREST policy for this table.
