#!/usr/bin/env bash
# Write apps/ios/Lumo.local.xcconfig from environment variables.
#
# The committed `apps/ios/Lumo.xcconfig` `#include?`s this file. When env
# vars are absent (CI, fresh clone) we still write the file with empty
# values so the include resolves cleanly — the app surfaces "config
# missing" UX rather than crashing. When the developer has sourced
# ~/.config/lumo/.env, real values flow in.
#
# Run this before `xcodegen generate`. It's safe to run repeatedly; it
# writes the same content given the same env.
#
# IMPORTANT: xcconfig treats `//` as a line comment with no escape
# syntax. We split URLs into scheme + host so values never contain
# `//`. The Swift side reassembles them.
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
out_path="$repo_root/apps/ios/Lumo.local.xcconfig"

supabase_url="${LUMO_SUPABASE_URL:-}"
supabase_anon_key="${LUMO_SUPABASE_ANON_KEY:-}"
elevenlabs_api_key="${LUMO_ELEVENLABS_API_KEY:-}"
elevenlabs_voice_id="${LUMO_ELEVENLABS_VOICE_ID:-}"

# Split URL → scheme + host (+ optional path) so xcconfig doesn't truncate.
supabase_scheme=""
supabase_host_path=""
if [[ -n "$supabase_url" ]]; then
  # Match leading scheme://. Default to https if scheme missing.
  if [[ "$supabase_url" =~ ^([a-z]+):// ]]; then
    supabase_scheme="${BASH_REMATCH[1]}"
    supabase_host_path="${supabase_url#${supabase_scheme}://}"
  else
    supabase_scheme="https"
    supabase_host_path="$supabase_url"
  fi
fi

cat > "$out_path" <<EOF
// AUTO-GENERATED by scripts/ios-write-xcconfig.sh — do not edit by hand.
// This file is gitignored. Real values come from ~/.config/lumo/.env.
//
// URL is split into scheme + host because xcconfig syntax treats \`//\`
// as a comment, so a URL like \`https://x.supabase.co\` would be
// truncated to \`https:\`. The Swift AppConfig reassembles them.
LUMO_SUPABASE_URL_SCHEME = ${supabase_scheme}
LUMO_SUPABASE_URL_HOST = ${supabase_host_path}
LUMO_SUPABASE_ANON_KEY = ${supabase_anon_key}
LUMO_ELEVENLABS_API_KEY = ${elevenlabs_api_key}
LUMO_ELEVENLABS_VOICE_ID = ${elevenlabs_voice_id}
EOF

# Warn separately for each missing piece so the developer knows which
# capability is unconfigured.
if [[ -z "$supabase_url" || -z "$supabase_anon_key" ]]; then
  echo "[ios-write-xcconfig] WARN: LUMO_SUPABASE_URL / LUMO_SUPABASE_ANON_KEY missing — auth will be disabled."
fi
if [[ -z "$elevenlabs_api_key" ]]; then
  echo "[ios-write-xcconfig] WARN: LUMO_ELEVENLABS_API_KEY missing — TTS falls through to AVSpeechSynthesizer."
fi

echo "[ios-write-xcconfig] wrote $out_path"
