"use client";

/**
 * Fixture-only page for FlightOffersSelectCard. Renders the card with
 * a deterministic three-offer payload and programmatically picks the
 * second row on mount so the playwright capture lands in the
 * "Selected" state (accent stripe + pill on row 2, rows 1 and 3 dim
 * to 40% opacity). The auto-pick targets a fixed offer_id so the
 * shot is reproducible across runs. Public route — middleware
 * doesn't gate /fixtures/*.
 */

import { useEffect, useRef } from "react";
import {
  FlightOffersSelectCard,
  type FlightOffersSelection,
} from "@/components/FlightOffersSelectCard";

const FIXTURE_PAYLOAD: FlightOffersSelection = {
  offers: [
    {
      offer_id: "off_united_morning",
      total_amount: "238.00",
      total_currency: "USD",
      owner: { name: "United", iata_code: "UA" },
      slices: [
        {
          origin: { iata_code: "SFO", city_name: "San Francisco" },
          destination: { iata_code: "LAS", city_name: "Las Vegas" },
          duration: "PT1H35M",
          segments: [
            {
              departing_at: "2026-05-09T07:15:00Z",
              arriving_at: "2026-05-09T08:50:00Z",
              marketing_carrier: { iata_code: "UA" },
              marketing_carrier_flight_number: "1234",
            },
          ],
        },
      ],
    },
    {
      offer_id: "off_frontier_midmorning",
      total_amount: "189.00",
      total_currency: "USD",
      owner: { name: "Frontier", iata_code: "F9" },
      slices: [
        {
          origin: { iata_code: "SFO", city_name: "San Francisco" },
          destination: { iata_code: "LAS", city_name: "Las Vegas" },
          duration: "PT1H30M",
          segments: [
            {
              departing_at: "2026-05-09T09:30:00Z",
              arriving_at: "2026-05-09T11:00:00Z",
              marketing_carrier: { iata_code: "F9" },
              marketing_carrier_flight_number: "1879",
            },
          ],
        },
      ],
    },
    {
      offer_id: "off_alaska_afternoon",
      total_amount: "274.50",
      total_currency: "USD",
      owner: { name: "Alaska", iata_code: "AS" },
      slices: [
        {
          origin: { iata_code: "SFO", city_name: "San Francisco" },
          destination: { iata_code: "LAS", city_name: "Las Vegas" },
          duration: "PT1H40M",
          segments: [
            {
              departing_at: "2026-05-09T14:50:00Z",
              arriving_at: "2026-05-09T16:30:00Z",
              marketing_carrier: { iata_code: "AS" },
              marketing_carrier_flight_number: "456",
            },
          ],
        },
      ],
    },
  ],
};

export default function FlightOffersFixture() {
  const ref = useRef<HTMLDivElement>(null);

  // Auto-pick the second row (Frontier) so playwright captures the
  // selected state without scripting the click. The query selector
  // matches the button generated by FlightOffersSelectCard's row
  // testid template — see flight-offers-row-${offer_id} in the
  // component.
  useEffect(() => {
    const handle = window.setTimeout(() => {
      const row = ref.current?.querySelector<HTMLButtonElement>(
        '[data-testid="flight-offers-row-off_frontier_midmorning"]',
      );
      row?.click();
    }, 50);
    return () => window.clearTimeout(handle);
  }, []);

  return (
    <main className="min-h-dvh bg-lumo-bg text-lumo-fg-high px-5 py-10">
      <div ref={ref} className="mx-auto max-w-2xl">
        <FlightOffersSelectCard
          payload={FIXTURE_PAYLOAD}
          // No-op onSubmit — fixture stays in the "selected, pre-
          // commit" visual state. The card's internal selectedId
          // remains set so the pill + dim-others stay rendered.
          onSubmit={() => {}}
        />
      </div>
    </main>
  );
}
